In [2]:
import numpy as np 

In [3]:
x= np.array([0,0,1,2,5])
res = np.amax(x)

In [4]:
res

np.int64(5)

In [5]:
x 

array([0, 0, 1, 2, 5])

In [7]:
x.shape[0]#数组元素个数

5

In [8]:
x.shape 

(5,)

In [11]:
import numpy as np

def to_categorical(x, n_col=None):
    if not n_col:
        n_col = np.amax(x) + 1
    print(n_col)
    one_hot = np.zeros((x.shape[0], n_col))
    print(one_hot[np.arange(x.shape[0]), x])
    one_hot[np.arange(x.shape[0]), x] = 1
    return one_hot

In [12]:
to_categorical(x)

6
[0. 0. 0. 0. 0.]


array([[1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.]])